module DUPLO_VNITRNI_KRUH(){
    intersection(){
        difference(){
            cube ([DUPLO_VNITRNI_KRUH_SIRKA_CTVERCE,DUPLO_VNITRNI_KRUH_SIRKA_CTVERCE,DUPLO_VYSKA]);
            
            translate ([(DUPLO_VNITRNI_KRUH_SIRKA_CTVERCE-DUPLO_VNITRNI_KRUH_SIRKA_VNITRNIHO_CTVERCE)/2,(DUPLO_VNITRNI_KRUH_SIRKA_CTVERCE-DUPLO_VNITRNI_KRUH_SIRKA_VNITRNIHO_CTVERCE)/2,0]) {
                cube ([DUPLO_VNITRNI_KRUH_SIRKA_VNITRNIHO_CTVERCE,DUPLO_VNITRNI_KRUH_SIRKA_VNITRNIHO_CTVERCE,DUPLO_VYSKA]);
                }
            }

        translate ([(DUPLO_VNITRNI_KRUH_SIRKA_CTVERCE)/2,(DUPLO_VNITRNI_KRUH_SIRKA_CTVERCE)/2,0]) {
            cylinder(r= DUPLO_VNITRNI_KRUH_SIRKA_CTVERCE/2, h=DUPLO_VYSKA ,$fn=DUPLO_KRUH);
            }
        }
    
    difference(){
        translate ([(DUPLO_VNITRNI_KRUH_SIRKA_CTVERCE)/2,(DUPLO_VNITRNI_KRUH_SIRKA_CTVERCE)/2,0]) {
            cylinder(r= DUPLO_VNITRNI_KRUH_SIRKA_CTVERCE/2, h=DUPLO_VYSKA ,$fn=DUPLO_KRUH);
            }
        translate ([(DUPLO_VNITRNI_KRUH_SIRKA_CTVERCE)/2,(DUPLO_VNITRNI_KRUH_SIRKA_CTVERCE)/2,0]) {
            cylinder(r= (DUPLO_VNITRNI_KRUH_SIRKA_CTVERCE/2)-DUPLO_VNITRNI_KRUH_SIRKA_STENY, h=DUPLO_VYSKA ,$fn=DUPLO_KRUH);
            }
            
        }
    
    }